{{- if and (not .Values.token.existingSecret) .Values.token.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reconciler.tokenSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reconciler.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "reconciler.tokenSecretKey" . }}: {{ .Values.token.value | quote }}
{{- end }}
